name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
    
    name: PHP ${{ matrix.php-version }} Tests
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl
        coverage: xdebug
    
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-

    - name: Configure GitHub token for Composer
      run: composer config github-oauth.github.com ${{ secrets.GH_COMPOSER_TOKEN }}
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Run test suite
      run: ./vendor/bin/atoum -c .atoum.php +verbose
      env:
        CI: true
        ENABLE_COVERAGE: ${{ matrix.php-version == '8.3' && 'true' || 'false' }}

    - name: Upload coverage to Codecov
      if: matrix.php-version == '8.3'
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Notify badge service
      if: always()
      run: |
        curl -X POST "https://gh-badges.bulton.fr/webhook" \
          -H "Content-Type: application/json" \
          -d "{\"secure_key\":\"${{ secrets.GH_BADGE_SECURE_KEY }}\",\"repository\":\"${{ github.repository }}\",\"branch\":\"${{ github.ref_name }}\",\"workflow_name\":\"${{ github.workflow }}\",\"job_name\":\"${{ github.job }}\",\"status\":\"${{ job.status }}\"}"

  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan Analysis
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl
        coverage: none
    
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-phpstan-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-phpstan-

    - name: Configure GitHub token for Composer
      run: composer config github-oauth.github.com ${{ secrets.GH_COMPOSER_TOKEN }}
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyse --memory-limit=1G

    - name: Notify badge service
      if: always()
      run: |
        curl -X POST "https://gh-badges.bulton.fr/webhook" \
          -H "Content-Type: application/json" \
          -d "{\"secure_key\":\"${{ secrets.GH_BADGE_SECURE_KEY }}\",\"repository\":\"${{ github.repository }}\",\"branch\":\"${{ github.ref_name }}\",\"workflow_name\":\"${{ github.workflow }}\",\"job_name\":\"${{ github.job }}\",\"status\":\"${{ job.status }}\"}"

  phpcs:
    runs-on: ubuntu-latest
    name: Code Style Check
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl
        coverage: none
    
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-phpcs-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-phpcs-

    - name: Configure GitHub token for Composer
      run: composer config github-oauth.github.com ${{ secrets.GH_COMPOSER_TOKEN }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHP CodeSniffer
      run: ./vendor/bin/phpcs

    - name: Notify badge service
      if: always()
      run: |
        curl -X POST "https://gh-badges.bulton.fr/webhook" \
          -H "Content-Type: application/json" \
          -d "{\"secure_key\":\"${{ secrets.GH_BADGE_SECURE_KEY }}\",\"repository\":\"${{ github.repository }}\",\"branch\":\"${{ github.ref_name }}\",\"workflow_name\":\"${{ github.workflow }}\",\"job_name\":\"${{ github.job }}\",\"status\":\"${{ job.status }}\"}"

  phpmd:
    runs-on: ubuntu-latest
    name: Mess Detector
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl
        coverage: none
    
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-phpmd-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-phpmd-

    - name: Configure GitHub token for Composer
      run: composer config github-oauth.github.com ${{ secrets.GH_COMPOSER_TOKEN }}
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Run PHPMD
      run: ./vendor/bin/phpmd src text cleancode,codesize,controversial,design,naming,unusedcode

    - name: Notify badge service
      if: always()
      run: |
        curl -X POST "https://gh-badges.bulton.fr/webhook" \
          -H "Content-Type: application/json" \
          -d "{\"secure_key\":\"${{ secrets.GH_BADGE_SECURE_KEY }}\",\"repository\":\"${{ github.repository }}\",\"branch\":\"${{ github.ref_name }}\",\"workflow_name\":\"${{ github.workflow }}\",\"job_name\":\"${{ github.job }}\",\"status\":\"${{ job.status }}\"}"