name: PHPStan Analysis

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan Analysis

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl
        coverage: none

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-phpstan-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-phpstan-

    - name: Configure GitHub token for Composer
      run: composer config github-oauth.github.com ${{ secrets.GH_COMPOSER_TOKEN }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyse --memory-limit=1G